import type { Metadata } from "next";
import { Figtree, Urbanist } from 'next/font/google';
import "./globals.css";


export const metadata: Metadata = {
  title: "Fame Tonic",
  description: "Generated by create next app",
};

const figtree = Figtree({
  variable: '--font-sans',
  subsets: ['latin'],
})
const urbanist = Urbanist({
  variable: '--font-mono',
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${figtree.variable} ${urbanist.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
